### Test PaSST on test set ###
# Normally only need to change `ckpt_path`

trainer:
  callbacks:
    # Show model profile before training start
    - class_path: util.callback.PrintAndLogModelProfile
    # # Generate a classification report and confusion matrix
    - class_path: util.result_analysis.ClassificationSummaryCallback
      init_args:
        feature_to_visualize: null  # embedding or logit
  logger:
      # Logger to save the logs, configs, hyperparameters and checkpoints
      class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        # Save path
        save_dir: log
        # Sub-path of the save path
        name: passt_test
        version: version_0

ckpt_path: null

model:
  class_path: model.lit_model.LitAcousticClassificationSystem
  init_args:
    backbone:
      class_path: model.backbone.LitPaSST
      init_args:
        pretrained: false
        num_classes: 13
    class_label: scene
    spec_extractor:
      class_path: util.spec_extractor.PaSSTMel
      init_args:
        n_mels: 128
        sr: &sr 32000
        freqm: 0
        timem: 0

data:
  # Wrapped data module of train, valid, test DataLoaders
  class_path: data.data_module_esas.ESASDataModule
  init_args:
    audio_dir: .../esas_data
    meta_dir: .../esas_metadata
    batch_size: 64
    num_workers: 4
    pin_memory: false
    clip_len: 10
    sampling_rate: *sr
    domain: mix_type
    test_subset: test
